# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"
  jobs:
    create_environment:
      - echo "Preparing environment"
      - pip install sphinx_rtd_theme
    build:
      html:
        - echo "Building HTML"
        - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Use Conda for runtime dependencies
conda:
  environment: environment.yml
